[package]
name = "starlight-fg"
version = "0.1.0"
authors = ["AlphaModder"]
edition = "2018"

[dependencies]
gfx-hal = { git = "https://github.com/gfx-rs/gfx" }
gfx-backend-vulkan = { git = "https://github.com/gfx-rs/gfx" }
daggy = "0.6"